#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := smart-mailbox

EXTRA_COMPONENT_DIRS =
	$(IDF_PATH)/examples/common_components/led_strip
	$(IDF_PATH)/examples/common_components/qrcode

include $(IDF_PATH)/make/project.mk

